# Generated by Django 5.2.8 on 2025-11-24 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('talk', 'Expert Talk'), ('podcast', 'Podcast')], help_text='Type of resource', max_length=16)),
                ('title', models.CharField(help_text='Resource title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Resource subtitle', max_length=160)),
                ('summary', models.TextField(blank=True, help_text='Resource summary')),
                ('category', models.CharField(blank=True, help_text='Resource category', max_length=120)),
                ('duration', models.CharField(blank=True, help_text='Resource duration', max_length=40)),
                ('media_url', models.URLField(blank=True, help_text='Media URL')),
                ('thumbnail', models.URLField(blank=True, help_text='Thumbnail URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether resource is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When resource was created')),
            ],
            options={
                'verbose_name': 'Guidance Resource',
                'verbose_name_plural': 'Guidance Resources',
                'ordering': ('resource_type', 'title'),
            },
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title', max_length=160, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Session subtitle', max_length=160)),
                ('description', models.TextField(blank=True, help_text='Session description')),
                ('category', models.CharField(help_text='Session category', max_length=60)),
                ('duration_minutes', models.PositiveIntegerField(default=5, help_text='Session duration in minutes')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level', max_length=20)),
                ('audio_url', models.URLField(blank=True, help_text='Audio file URL')),
                ('video_url', models.URLField(blank=True, help_text='Video file URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether session is featured')),
                ('thumbnail', models.URLField(blank=True, help_text='Thumbnail URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When session was last updated')),
            ],
            options={
                'verbose_name': 'Meditation Session',
                'verbose_name_plural': 'Meditation Sessions',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MindCareBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Booster title', max_length=160, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Booster subtitle', max_length=160)),
                ('description', models.TextField(blank=True, help_text='Booster description')),
                ('category', models.CharField(choices=[('breathing', 'Breathing'), ('audio', 'Audio'), ('movement', 'Movement'), ('reflection', 'Reflection')], default='breathing', help_text='Booster category', max_length=32)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=40)),
                ('action_label', models.CharField(default='Start', help_text='Action button label', max_length=60)),
                ('prompt', models.TextField(blank=True, help_text='Booster prompt text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('estimated_seconds', models.PositiveIntegerField(default=120, help_text='Estimated duration in seconds')),
                ('resource_url', models.URLField(blank=True, help_text='Resource URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When booster was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When booster was last updated')),
            ],
            options={
                'verbose_name': 'Mind Care Booster',
                'verbose_name_plural': 'Mind Care Boosters',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Track title', max_length=160, unique=True)),
                ('description', models.TextField(blank=True, help_text='Track description')),
                ('duration_seconds', models.PositiveIntegerField(default=180, help_text='Track duration in seconds')),
                ('audio_url', models.URLField(blank=True, help_text='Audio file URL')),
                ('mood', models.CharField(choices=[('calm', 'Calm'), ('focus', 'Focus'), ('sleep', 'Sleep'), ('uplift', 'Uplift')], default='calm', help_text='Mood category', max_length=20)),
                ('thumbnail', models.URLField(blank=True, help_text='Thumbnail URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When track was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When track was last updated')),
            ],
            options={
                'verbose_name': 'Music Track',
                'verbose_name_plural': 'Music Tracks',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Group name', max_length=160)),
                ('description', models.TextField(blank=True, help_text='Group description')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When group was created')),
            ],
            options={
                'verbose_name': 'Support Group',
                'verbose_name_plural': 'Support Groups',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', help_text='Current status of the chat', max_length=20)),
                ('initial_message', models.TextField(blank=True, help_text='Initial message from user when creating the chat')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the chat was created')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, help_text='When the chat became active (counselor accepted or user sent message)', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the chat ended (completed or cancelled)', null=True)),
                ('last_user_activity', models.DateTimeField(blank=True, db_index=True, help_text='When the user last interacted with this chat (sending message or opening chat)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp')),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount billed for this chat (in rupees)', max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Total active chat duration in minutes (for billing calculation)')),
                ('is_billed', models.BooleanField(db_index=True, default=False, help_text='Whether billing has been processed and wallet deducted')),
                ('billing_processed_at', models.DateTimeField(blank=True, help_text='When billing was processed', null=True)),
                ('counsellor', models.ForeignKey(blank=True, help_text='Counselor assigned to this chat (null for queued chats)', limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who initiated this chat', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Message content')),
                ('client_message_id', models.CharField(blank=True, db_index=True, help_text='Client-generated UUID for deduplication', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When message was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When message was last updated')),
                ('chat', models.ForeignKey(help_text='Chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chat')),
                ('sender', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CounsellorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, help_text="Counselor's area of specialization", max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages spoken')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.00 to 5.00)', max_digits=3)),
                ('is_available', models.BooleanField(default=True, help_text='Whether counselor is currently available')),
                ('bio', models.TextField(blank=True, help_text="Counselor's biography")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When profile was last updated')),
                ('user', models.OneToOneField(help_text='Associated Django User (must be a counselor)', on_delete=django.db.models.deletion.CASCADE, related_name='counsellorprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Counselor Profile',
                'verbose_name_plural': 'Counselor Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, help_text="Doctor's area of specialization", max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('license_number', models.CharField(blank=True, help_text='Medical license number', max_length=100)),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages spoken')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.00 to 5.00)', max_digits=3)),
                ('is_available', models.BooleanField(default=True, help_text='Whether doctor is currently available')),
                ('bio', models.TextField(blank=True, help_text="Doctor's biography")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When profile was last updated')),
                ('user', models.OneToOneField(help_text='Associated Django User (must be a doctor)', on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('code', models.CharField(help_text='OTP code', max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password reset')], help_text='OTP purpose', max_length=32)),
                ('token', models.CharField(help_text='Unique verification token', max_length=64, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP is verified')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts')),
                ('expires_at', models.DateTimeField(help_text='When OTP expires')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When OTP was created')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was verified', null=True)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'purpose', 'is_verified'], name='api_emailot_email_ab57e8_idx'), models.Index(fields=['token'], name='api_emailot_token_79673b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(help_text='Mood value (1-5 scale)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When mood was recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When log was created')),
                ('user', models.ForeignKey(help_text='User who recorded this mood', on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Log',
                'verbose_name_plural': 'Mood Logs',
                'ordering': ('-recorded_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When user joined the group')),
                ('group', models.ForeignKey(help_text='Support group', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.supportgroup')),
                ('user', models.ForeignKey(help_text='User who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='support_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Group Membership',
                'verbose_name_plural': 'Support Group Memberships',
                'ordering': ('-joined_at',),
            },
        ),
        migrations.CreateModel(
            name='UpcomingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title', max_length=180)),
                ('session_type', models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group'), ('workshop', 'Workshop'), ('webinar', 'Webinar')], help_text='Type of session', max_length=40)),
                ('start_time', models.DateTimeField(help_text='Scheduled start time')),
                ('counsellor_name', models.CharField(help_text='Name of the counselor', max_length=160)),
                ('notes', models.TextField(blank=True, help_text='Session notes (confidential notes for counselor)')),
                ('is_confirmed', models.BooleanField(default=True, help_text='Whether session is confirmed')),
                ('actual_start_time', models.DateTimeField(blank=True, db_index=True, help_text='When session actually started (not scheduled time)', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, db_index=True, help_text='When session actually ended', null=True)),
                ('session_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', help_text='Current status of the session', max_length=20)),
                ('risk_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='none', help_text='Risk level assessment', max_length=20)),
                ('manual_flag', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', help_text='Manual flag set by counselor', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When session was last updated')),
                ('counsellor', models.ForeignKey(blank=True, help_text='Counselor assigned to this session', limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who scheduled this session', on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upcoming Session',
                'verbose_name_plural': 'Upcoming Sessions',
                'ordering': ('start_time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text="User's full name", max_length=120)),
                ('nickname', models.CharField(blank=True, help_text="User's preferred nickname", max_length=80)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=30)),
                ('age', models.PositiveIntegerField(blank=True, help_text="User's age", null=True)),
                ('gender', models.CharField(blank=True, help_text="User's gender", max_length=50)),
                ('wallet_minutes', models.PositiveIntegerField(default=100, help_text='Available minutes in wallet for services')),
                ('last_mood', models.PositiveSmallIntegerField(default=3, help_text='Last recorded mood value (1-5 scale)')),
                ('last_mood_updated', models.DateTimeField(blank=True, help_text='When mood was last updated', null=True)),
                ('mood_updates_count', models.PositiveSmallIntegerField(default=0, help_text='Total number of mood updates')),
                ('mood_updates_date', models.DateField(blank=True, help_text='Date of last mood update', null=True)),
                ('timezone', models.CharField(blank=True, help_text="User's timezone (e.g., 'Asia/Kolkata')", max_length=64)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Whether notifications are enabled')),
                ('prefers_dark_mode', models.BooleanField(default=False, help_text='Whether user prefers dark mode')),
                ('language', models.CharField(default='English', help_text='Preferred language', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When profile was last updated')),
                ('user', models.OneToOneField(help_text='Associated Django User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='WellnessJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Entry title', max_length=160)),
                ('note', models.TextField(help_text='Journal entry content')),
                ('mood', models.CharField(help_text='Mood at time of entry', max_length=16)),
                ('entry_type', models.CharField(choices=[('3-Day Journal', '3-Day Journal'), ('Weekly Journal', 'Weekly Journal'), ('Custom', 'Custom')], help_text='Type of journal entry', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When entry was last updated')),
                ('user', models.ForeignKey(help_text='User who owns this journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='wellness_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wellness Journal Entry',
                'verbose_name_plural': 'Wellness Journal Entries',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WellnessTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=150)),
                ('category', models.CharField(choices=[('daily', 'Daily'), ('evening', 'Evening')], help_text='Task category', max_length=20)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether task is completed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When task was last updated')),
                ('user', models.ForeignKey(help_text='User who owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='wellness_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wellness Task',
                'verbose_name_plural': 'Wellness Tasks',
                'ordering': ('category', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('video', 'Video Call'), ('voice', 'Voice Call')], default='video', help_text='Type of call (video or voice)', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the call', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When call is scheduled', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When call started', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When call ended', null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Call duration in seconds')),
                ('notes', models.TextField(blank=True, help_text='Post-call notes or summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When call was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When call was last updated')),
                ('counsellor', models.ForeignKey(blank=True, help_text='Counselor for this call', limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_calls', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who initiated the call', on_delete=django.db.models.deletion.CASCADE, related_name='user_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_call_user_id_7ec5bd_idx'), models.Index(fields=['counsellor', '-created_at'], name='api_call_counsel_d24a7e_idx'), models.Index(fields=['status', '-created_at'], name='api_call_status_c54384_idx'), models.Index(fields=['counsellor', 'status'], name='api_call_counsel_1aa668_idx'), models.Index(fields=['scheduled_at', 'status'], name='api_call_schedul_bbb190_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-created_at'], name='api_chat_user_id_53a809_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['counsellor', '-created_at'], name='api_chat_counsel_803a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['status', '-created_at'], name='api_chat_status_2a3577_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['counsellor', 'status'], name='api_chat_counsel_b6e460_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['status', 'counsellor'], name='chat_queued_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='api_chatmes_chat_id_5d8e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='api_chatmes_sender__d0513b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', '-created_at'], name='api_chatmes_chat_id_c99b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'client_message_id'], name='chat_client_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'client_message_id'], name='sender_client_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('sender', 'client_message_id'), name='unique_client_message_per_sender'),
        ),
        migrations.AddIndex(
            model_name='moodlog',
            index=models.Index(fields=['user', '-recorded_at'], name='api_moodlog_user_id_90bd77_idx'),
        ),
        migrations.AddIndex(
            model_name='moodlog',
            index=models.Index(fields=['user', 'value', '-recorded_at'], name='api_moodlog_user_id_76d00a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supportgroupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['user', 'start_time'], name='api_upcomin_user_id_559aac_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['counsellor', 'start_time'], name='api_upcomin_counsel_e1352f_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['start_time', 'is_confirmed'], name='api_upcomin_start_t_91efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['counsellor', 'session_status'], name='api_upcomin_counsel_d3aaf7_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['session_status', 'actual_start_time'], name='api_upcomin_session_230ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='api_userpro_user_id_ea9cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['wallet_minutes'], name='api_userpro_wallet__a34a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnessjournalentry',
            index=models.Index(fields=['user', '-created_at'], name='api_wellnes_user_id_d36e33_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnessjournalentry',
            index=models.Index(fields=['user', 'entry_type', '-created_at'], name='api_wellnes_user_id_161039_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnesstask',
            index=models.Index(fields=['user', 'category', 'is_completed'], name='api_wellnes_user_id_627049_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnesstask',
            index=models.Index(fields=['user', '-created_at'], name='api_wellnes_user_id_d281f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wellnesstask',
            unique_together={('user', 'title', 'category')},
        ),
    ]
