# Generated by Django 5.2.8 on 2025-12-06 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assessment title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Assessment description')),
                ('category', models.CharField(blank=True, help_text='Assessment category (e.g., Depression, Anxiety, Stress)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether assessment is available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When assessment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When assessment was last updated')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('scale', 'Scale'), ('text', 'Text')], default='multiple_choice', help_text='Type of question', max_length=50)),
                ('options', models.JSONField(blank=True, default=list, help_text='Answer options (for multiple choice or scale)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When question was created')),
                ('assessment', models.ForeignKey(help_text='Parent assessment', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text="User's answers (question_id -> answer)")),
                ('total_score', models.FloatField(blank=True, help_text='Total assessment score', null=True)),
                ('result_category', models.CharField(choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], help_text='Result category', max_length=20)),
                ('recommendations', models.TextField(blank=True, help_text='Personalized recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When assessment was completed')),
                ('assessment', models.ForeignKey(help_text='Assessment taken', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.assessment')),
                ('user', models.ForeignKey(help_text='User who took the assessment', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'verbose_name_plural': 'Assessment Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
