# Generated by Django 5.2.8 on 2025-12-07 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessment_assessmentquestion_assessmentresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='value',
            field=models.DecimalField(decimal_places=1, help_text='Mood value (1-5 scale with half-point precision, e.g., 1.5, 2.5, 3.5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_mood',
            field=models.DecimalField(decimal_places=1, default=3.0, help_text='Last recorded mood value (1-5 scale with half-point precision, e.g., 1.5, 2.5, 3.5)', max_digits=3),
        ),
        migrations.CreateModel(
            name='CounsellorTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Start time of availability')),
                ('end_time', models.TimeField(help_text='End time of availability')),
                ('is_available', models.BooleanField(default=True, help_text='Whether slot is available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When slot was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When slot was last updated')),
                ('counsellor', models.ForeignKey(help_text='Counselor user', limit_choices_to={'counsellorprofile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Counselor Time Slot',
                'verbose_name_plural': 'Counselor Time Slots',
                'indexes': [models.Index(fields=['counsellor', 'day_of_week'], name='api_counsel_counsel_6c1a0f_idx'), models.Index(fields=['counsellor', 'is_available'], name='api_counsel_counsel_71b05a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(help_text='Entry title', max_length=200)),
                ('emoji', models.CharField(blank=True, help_text='Emoji or short label', max_length=32)),
                ('date', models.DateField(help_text='Entry date')),
                ('write_something', models.TextField(help_text='Journal content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When entry was last updated')),
                ('user', models.ForeignKey(help_text='Owner of entry', on_delete=django.db.models.deletion.CASCADE, related_name='my_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Journal Entry',
                'verbose_name_plural': 'My Journal Entries',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['user', '-date'], name='api_myjourn_user_id_da5c93_idx'), models.Index(fields=['user', '-created_at'], name='api_myjourn_user_id_8eef04_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1-5 stars')),
                ('feedback', models.TextField(blank=True, help_text='Optional written feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When rating was created')),
                ('counsellor', models.ForeignKey(help_text='Counsellor being rated', limit_choices_to={'counsellorprofile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(help_text='The session being rated', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.upcomingsession')),
                ('user', models.ForeignKey(help_text='User who gave rating', on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Rating',
                'verbose_name_plural': 'Session Ratings',
                'indexes': [models.Index(fields=['counsellor', '-created_at'], name='api_session_counsel_0d6812_idx'), models.Index(fields=['user', '-created_at'], name='api_session_user_id_94a252_idx'), models.Index(fields=['session'], name='api_session_session_789b32_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_category', models.CharField(choices=[('anxiety', 'Anxiety'), ('depression', 'Depression'), ('stress', 'Stress'), ('relationship', 'Relationship Issues'), ('work', 'Work/Career'), ('family', 'Family Issues'), ('trauma', 'Trauma'), ('substance', 'Substance Use'), ('eating', 'Eating Disorders'), ('sleep', 'Sleep Issues'), ('other', 'Other')], default='other', help_text='Category of the issue discussed', max_length=50)),
                ('feedback_text', models.TextField(help_text='Feedback notes about the user and their issues')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the feedback', max_length=20)),
                ('is_private', models.BooleanField(default=False, help_text='Whether this feedback is private (only visible to the counsellor who wrote it)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When feedback was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When feedback was last updated')),
                ('chat', models.ForeignKey(blank=True, help_text='Optional reference to the chat session this feedback relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='api.chat')),
                ('counsellor', models.ForeignKey(help_text='Counsellor who wrote this feedback', limit_choices_to={'counsellorprofile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User this feedback is about', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_userfee_user_id_538c17_idx'), models.Index(fields=['counsellor', '-created_at'], name='api_userfee_counsel_87f0f7_idx'), models.Index(fields=['user', 'is_private'], name='api_userfee_user_id_ffa943_idx'), models.Index(fields=['issue_category', '-created_at'], name='api_userfee_issue_c_600f76_idx'), models.Index(fields=['priority', '-created_at'], name='api_userfee_priorit_fc6338_idx')],
            },
        ),
    ]
