from django.urls import path
# TokenRefreshView is now imported from views

from .views import (
    AssessmentDetailView,
    AssessmentListView,
    AssessmentResultDetailView,
    AssessmentResultsListView,
    AssessmentSubmitView,
    ChatAcceptView,
    ChatCreateView,
    ChatFilteredListView,
    ChatListView,
    ChatMessageListView,
    ChatTranscriptView,
    CounsellorAppointmentsView,
    CounsellorProfileView,
    CounsellorStatsView,
    DashboardView,
    EmailOrUsernameTokenObtainPairView,
    LegacyAdvancedCareSupportView,
    LegacyAffirmationsView,
    LegacyAssessmentView,
    LegacyBreathingView,
    LegacyExpertConnectView,
    LegacyFeatureDetailView,
    LegacyGuidelinesView,
    MeditationSessionListView,
    MindCareBoosterListView,
    MoodUpdateView,
    MoodHistoryView,
    MoodAnalyticsView,
    MusicTrackListView,
    PasswordResetSendOTPView,
    PasswordResetVerifyOTPView,
    PasswordResetView,
    ProfessionalGuidanceListView,
    ProfileView,
    QueuedChatsView,
    QuickSessionView,
    RegisterView,
    RegistrationSendOTPView,
    RegistrationVerifyOTPView,
    ReportsAnalyticsView,
    SessionDurationView,
    SessionEndView,
    SessionHistoryView,
    SessionRatingCreateView,
    SessionRatingDetailView,
    SessionRatingListView,
    SessionStartView,
    SessionSummaryView,
    SessionUpdateView,
    SupportGroupListView,
    TokenRefreshView,
    UpcomingSessionDetailView,
    UpcomingSessionListCreateView,
    UserSettingsView,
    WalletDetailView,
    WalletRechargeView,
    WalletUsageView,
    WellnessJournalEntryDetailView,
    WellnessJournalEntryListCreateView,
    WellnessTaskDetailView,
    WellnessTaskListCreateView,
    MyJournalListCreateView,
    MyJournalDetailView,
)
from .views.health_views import HealthCheckView
from .views.call_views import (
    CallAcceptView,
    CallCreateView,
    CallDetailView,
    CallEndView,
    CallHistoryView,
    CallListView,
    CallTokenView,
    QueuedCallsView,
    get_turn_credentials_view,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view()),
    path("auth/register/", RegisterView.as_view()),
    path("auth/send-otp/", RegistrationSendOTPView.as_view()),
    path("auth/verify-otp/", RegistrationVerifyOTPView.as_view()),
    path("auth/send-password-reset-otp/", PasswordResetSendOTPView.as_view()),
    path("auth/verify-password-reset-otp/", PasswordResetVerifyOTPView.as_view()),
    path("auth/password-reset/", PasswordResetView.as_view()),
    path("auth/token/", EmailOrUsernameTokenObtainPairView.as_view()),
    path("auth/token/refresh/", TokenRefreshView.as_view()),
    path("profile/", ProfileView.as_view()),
    path("settings/", UserSettingsView.as_view()),
    path("dashboard/", DashboardView.as_view()),
    path("mood/", MoodUpdateView.as_view()),
    path("mood/history/", MoodHistoryView.as_view()),
    path("mood/analytics/", MoodAnalyticsView.as_view()),
    path("wallet/", WalletDetailView.as_view()),
    path("wallet/recharge/", WalletRechargeView.as_view()),
    path("wallet/use/", WalletUsageView.as_view()),
    path("wellness/tasks/", WellnessTaskListCreateView.as_view()),
    path("wellness/tasks/<int:task_id>/", WellnessTaskDetailView.as_view()),
    path("wellness/journals/", WellnessJournalEntryListCreateView.as_view()),
    path("wellness/journals/<int:entry_id>/", WellnessJournalEntryDetailView.as_view()),
    path("wellness/my-journal/", MyJournalListCreateView.as_view()),
    path("wellness/my-journal/<int:entry_id>/", MyJournalDetailView.as_view()),
    path("support-groups/", SupportGroupListView.as_view()),
    path("sessions/", UpcomingSessionListCreateView.as_view()),
    path("sessions/history/", SessionHistoryView.as_view()),
    path("sessions/<int:session_id>/", UpcomingSessionDetailView.as_view()),
    path("sessions/<int:session_id>/start/", SessionStartView.as_view()),
    path("sessions/<int:session_id>/end/", SessionEndView.as_view()),
    path("sessions/<int:session_id>/duration/", SessionDurationView.as_view()),
    path("sessions/<int:session_id>/update/", SessionUpdateView.as_view()),
    path("sessions/<int:session_id>/summary/", SessionSummaryView.as_view()),
    path("sessions/quick/", QuickSessionView.as_view()),
    path("sessions/ratings/", SessionRatingListView.as_view()),
    path("sessions/ratings/create/", SessionRatingCreateView.as_view()),
    path("sessions/ratings/<int:rating_id>/", SessionRatingDetailView.as_view()),
    path("reports/analytics/", ReportsAnalyticsView.as_view()),
    path("guidance/resources/", ProfessionalGuidanceListView.as_view()),
    path("content/music/", MusicTrackListView.as_view()),
    path("content/boosters/", MindCareBoosterListView.as_view()),
    path("content/meditations/", MeditationSessionListView.as_view()),
    path("legacy/guidelines/", LegacyGuidelinesView.as_view()),
    path("legacy/expert-connect/", LegacyExpertConnectView.as_view()),
    path("legacy/breathing/", LegacyBreathingView.as_view()),
    path("legacy/assessment/", LegacyAssessmentView.as_view()),
    path("legacy/affirmations/", LegacyAffirmationsView.as_view()),
    path("legacy/advanced-care/", LegacyAdvancedCareSupportView.as_view()),
    path("legacy/feature-detail/", LegacyFeatureDetailView.as_view()),
    # Counselor endpoints
    path("counselor/profile/", CounsellorProfileView.as_view()),
    path("counselor/appointments/", CounsellorAppointmentsView.as_view()),
    path("counselor/stats/", CounsellorStatsView.as_view()),
    path("counselor/queued-chats/", QueuedChatsView.as_view()),
    # Chat endpoints
    path("chats/", ChatCreateView.as_view()),
    path("chats/list/", ChatListView.as_view()),
    path("chats/filtered/", ChatFilteredListView.as_view()),
    path("chats/<int:chat_id>/accept/", ChatAcceptView.as_view()),
    path("chats/<int:chat_id>/messages/", ChatMessageListView.as_view()),
    path("chats/<int:chat_id>/transcript/", ChatTranscriptView.as_view()),
    # WebRTC/Call endpoints
    path("calls/create/", CallCreateView.as_view(), name="create_call"),
    path("calls/turn-credentials/", get_turn_credentials_view, name="turn_credentials"),
    path("calls/", CallListView.as_view(), name="call_list"),
    path("calls/<int:pk>/", CallDetailView.as_view(), name="call_detail"),
    path("calls/<int:call_id>/accept/", CallAcceptView.as_view(), name="call_accept"),
    path("calls/<int:call_id>/token/", CallTokenView.as_view(), name="call_token"),
    path("calls/<int:call_id>/end/", CallEndView.as_view(), name="end_call"),
    path("calls/queued/", QueuedCallsView.as_view(), name="queued_calls"),
    path("calls/history/", CallHistoryView.as_view(), name="call_history"),
    # Assessment endpoints
    path("assessments/", AssessmentListView.as_view()),
    path("assessments/<int:pk>/", AssessmentDetailView.as_view()),
    path("assessments/<int:assessment_id>/submit/", AssessmentSubmitView.as_view()),
    path("assessments/results/", AssessmentResultsListView.as_view()),
    path("assessments/results/<int:pk>/", AssessmentResultDetailView.as_view()),
]

