"""
Django management command to create missing database tables.
This creates only the tables that don't exist yet.
"""
from django.core.management.base import BaseCommand
from django.db import connection


class Command(BaseCommand):
    help = 'Create missing database tables by executing SQL statements'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS("\n" + "=" * 100))
        self.stdout.write(self.style.SUCCESS("CREATING MISSING DATABASE TABLES"))
        self.stdout.write(self.style.SUCCESS("=" * 100))
        
        # Missing tables SQL statements (from migration 0001)
        table_sqls = {
            'api_call': '''CREATE TABLE IF NOT EXISTS "api_call" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "call_type" varchar(20) NOT NULL,
                "status" varchar(20) NOT NULL,
                "scheduled_at" timestamp with time zone NULL,
                "started_at" timestamp with time zone NULL,
                "ended_at" timestamp with time zone NULL,
                "duration_seconds" integer NOT NULL CHECK ("duration_seconds" >= 0),
                "notes" text NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "counsellor_id" integer NULL,
                "user_id" integer NOT NULL
            );''',
            'api_chat': '''CREATE TABLE IF NOT EXISTS "api_chat" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "status" varchar(20) NOT NULL,
                "initial_message" text NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "started_at" timestamp with time zone NULL,
                "ended_at" timestamp with time zone NULL,
                "last_user_activity" timestamp with time zone NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "billed_amount" numeric(10, 2) NOT NULL,
                "duration_minutes" integer NOT NULL CHECK ("duration_minutes" >= 0),
                "is_billed" boolean NOT NULL,
                "billing_processed_at" timestamp with time zone NULL,
                "counsellor_id" integer NULL,
                "user_id" integer NOT NULL
            );''',
            'api_chatmessage': '''CREATE TABLE IF NOT EXISTS "api_chatmessage" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "text" text NOT NULL,
                "client_message_id" varchar(64) NULL,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "chat_id" bigint NOT NULL,
                "sender_id" integer NOT NULL
            );''',
            'api_counsellorprofile': '''CREATE TABLE IF NOT EXISTS "api_counsellorprofile" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "specialization" varchar(200) NOT NULL,
                "experience_years" integer NOT NULL CHECK ("experience_years" >= 0),
                "languages" jsonb NOT NULL,
                "rating" numeric(3, 2) NOT NULL,
                "is_available" boolean NOT NULL,
                "bio" text NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "user_id" integer NOT NULL UNIQUE
            );''',
            'api_doctorprofile': '''CREATE TABLE IF NOT EXISTS "api_doctorprofile" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "specialization" varchar(200) NOT NULL,
                "experience_years" integer NOT NULL CHECK ("experience_years" >= 0),
                "license_number" varchar(100) NOT NULL,
                "languages" jsonb NOT NULL,
                "rating" numeric(3, 2) NOT NULL,
                "is_available" boolean NOT NULL,
                "bio" text NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "user_id" integer NOT NULL UNIQUE
            );''',
            'api_meditationsession': '''CREATE TABLE IF NOT EXISTS "api_meditationsession" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "title" varchar(160) NOT NULL UNIQUE,
                "subtitle" varchar(160) NOT NULL,
                "description" text NOT NULL,
                "category" varchar(60) NOT NULL,
                "duration_minutes" integer NOT NULL CHECK ("duration_minutes" >= 0),
                "difficulty" varchar(20) NOT NULL,
                "audio_url" varchar(200) NOT NULL,
                "video_url" varchar(200) NOT NULL,
                "is_featured" boolean NOT NULL,
                "thumbnail" varchar(200) NOT NULL,
                "order" integer NOT NULL CHECK ("order" >= 0),
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL
            );''',
            'api_mindcarebooster': '''CREATE TABLE IF NOT EXISTS "api_mindcarebooster" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "title" varchar(160) NOT NULL UNIQUE,
                "subtitle" varchar(160) NOT NULL,
                "description" text NOT NULL,
                "category" varchar(32) NOT NULL,
                "icon" varchar(40) NOT NULL,
                "action_label" varchar(60) NOT NULL,
                "prompt" text NOT NULL,
                "order" integer NOT NULL CHECK ("order" >= 0),
                "estimated_seconds" integer NOT NULL CHECK ("estimated_seconds" >= 0),
                "resource_url" varchar(200) NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL
            );''',
            'api_musictrack': '''CREATE TABLE IF NOT EXISTS "api_musictrack" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "title" varchar(160) NOT NULL UNIQUE,
                "description" text NOT NULL,
                "duration_seconds" integer NOT NULL CHECK ("duration_seconds" >= 0),
                "audio_url" varchar(200) NOT NULL,
                "mood" varchar(20) NOT NULL,
                "thumbnail" varchar(200) NOT NULL,
                "order" integer NOT NULL CHECK ("order" >= 0),
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL
            );''',
        }
        
        # Get existing tables
        existing_tables = self.get_existing_tables()
        
        # Filter to only missing ones
        tables_to_create = [t for t in table_sqls.keys() if t not in existing_tables]
        
        if not tables_to_create:
            self.stdout.write(self.style.SUCCESS("\n[OK] All tables already exist!"))
            return
        
        self.stdout.write(f"\nMissing tables to create: {len(tables_to_create)}")
        for table in tables_to_create:
            self.stdout.write(f"  - {table}")
        
        # Create tables
        self.stdout.write("\n" + "=" * 100)
        self.stdout.write("Creating tables...")
        self.stdout.write("=" * 100)
        
        created_count = 0
        with connection.cursor() as cursor:
            for table_name in tables_to_create:
                try:
                    self.stdout.write(f"\nCreating table: {table_name}")
                    cursor.execute(table_sqls[table_name])
                    created_count += 1
                    self.stdout.write(self.style.SUCCESS(f"  [OK] Created {table_name}"))
                except Exception as e:
                    error_msg = str(e)
                    if 'already exists' in error_msg.lower():
                        self.stdout.write(self.style.WARNING(f"  [SKIP] {table_name} already exists"))
                        created_count += 1
                    else:
                        self.stdout.write(self.style.ERROR(f"  [ERROR] Failed to create {table_name}: {error_msg[:100]}"))
        
        self.stdout.write("\n" + "=" * 100)
        self.stdout.write(self.style.SUCCESS(f"COMPLETED: Created {created_count} out of {len(tables_to_create)} tables"))
        self.stdout.write("=" * 100)
        
        # Mark migration as applied
        if created_count > 0:
            self.stdout.write("\nMarking migration as applied...")
            try:
                from django.core.management import call_command
                call_command('migrate', 'api', '0001', '--fake', verbosity=0)
                self.stdout.write(self.style.SUCCESS("[OK] Migration marked as applied"))
            except Exception as e:
                self.stdout.write(self.style.WARNING(f"[WARNING] Could not mark migration as applied: {e}"))
    
    def get_existing_tables(self):
        """Get all existing tables in the database."""
        tables = []
        
        with connection.cursor() as cursor:
            if connection.vendor == 'sqlite':
                cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
            elif connection.vendor == 'postgresql':
                cursor.execute("""
                    SELECT table_name 
                    FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_type = 'BASE TABLE'
                    ORDER BY table_name;
                """)
            else:
                cursor.execute("""
                    SELECT table_name 
                    FROM information_schema.tables 
                    WHERE table_schema = DATABASE()
                    AND table_type = 'BASE TABLE'
                    ORDER BY table_name;
                """)
            
            rows = cursor.fetchall()
            for row in rows:
                tables.append(row[0])
        
        return set(tables)

