-- SQL to create missing tables
-- Run this using: python manage.py dbshell < create_missing_tables.sql
-- Or execute these statements one by one

-- Create api_call table
CREATE TABLE IF NOT EXISTS "api_call" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "call_type" varchar(20) NOT NULL,
    "status" varchar(20) NOT NULL,
    "scheduled_at" timestamp with time zone NULL,
    "started_at" timestamp with time zone NULL,
    "ended_at" timestamp with time zone NULL,
    "duration_seconds" integer NOT NULL CHECK ("duration_seconds" >= 0),
    "notes" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "counsellor_id" integer NULL,
    "user_id" integer NOT NULL
);

-- Create api_chat table
CREATE TABLE IF NOT EXISTS "api_chat" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "status" varchar(20) NOT NULL,
    "initial_message" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "started_at" timestamp with time zone NULL,
    "ended_at" timestamp with time zone NULL,
    "last_user_activity" timestamp with time zone NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "billed_amount" numeric(10, 2) NOT NULL,
    "duration_minutes" integer NOT NULL CHECK ("duration_minutes" >= 0),
    "is_billed" boolean NOT NULL,
    "billing_processed_at" timestamp with time zone NULL,
    "counsellor_id" integer NULL,
    "user_id" integer NOT NULL
);

-- Create api_chatmessage table
CREATE TABLE IF NOT EXISTS "api_chatmessage" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "text" text NOT NULL,
    "client_message_id" varchar(64) NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "chat_id" bigint NOT NULL,
    "sender_id" integer NOT NULL
);

-- Create api_counsellorprofile table
CREATE TABLE IF NOT EXISTS "api_counsellorprofile" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "specialization" varchar(200) NOT NULL,
    "experience_years" integer NOT NULL CHECK ("experience_years" >= 0),
    "languages" jsonb NOT NULL,
    "rating" numeric(3, 2) NOT NULL,
    "is_available" boolean NOT NULL,
    "bio" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL UNIQUE
);

-- Create api_doctorprofile table
CREATE TABLE IF NOT EXISTS "api_doctorprofile" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "specialization" varchar(200) NOT NULL,
    "experience_years" integer NOT NULL CHECK ("experience_years" >= 0),
    "license_number" varchar(100) NOT NULL,
    "languages" jsonb NOT NULL,
    "rating" numeric(3, 2) NOT NULL,
    "is_available" boolean NOT NULL,
    "bio" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL UNIQUE
);

-- Create api_meditationsession table
CREATE TABLE IF NOT EXISTS "api_meditationsession" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(160) NOT NULL UNIQUE,
    "subtitle" varchar(160) NOT NULL,
    "description" text NOT NULL,
    "category" varchar(60) NOT NULL,
    "duration_minutes" integer NOT NULL CHECK ("duration_minutes" >= 0),
    "difficulty" varchar(20) NOT NULL,
    "audio_url" varchar(200) NOT NULL,
    "video_url" varchar(200) NOT NULL,
    "is_featured" boolean NOT NULL,
    "thumbnail" varchar(200) NOT NULL,
    "order" integer NOT NULL CHECK ("order" >= 0),
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

-- Create api_mindcarebooster table
CREATE TABLE IF NOT EXISTS "api_mindcarebooster" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(160) NOT NULL UNIQUE,
    "subtitle" varchar(160) NOT NULL,
    "description" text NOT NULL,
    "category" varchar(32) NOT NULL,
    "icon" varchar(40) NOT NULL,
    "action_label" varchar(60) NOT NULL,
    "prompt" text NOT NULL,
    "order" integer NOT NULL CHECK ("order" >= 0),
    "estimated_seconds" integer NOT NULL CHECK ("estimated_seconds" >= 0),
    "resource_url" varchar(200) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

-- Create api_musictrack table
CREATE TABLE IF NOT EXISTS "api_musictrack" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(160) NOT NULL UNIQUE,
    "description" text NOT NULL,
    "duration_seconds" integer NOT NULL CHECK ("duration_seconds" >= 0),
    "audio_url" varchar(200) NOT NULL,
    "mood" varchar(20) NOT NULL,
    "thumbnail" varchar(200) NOT NULL,
    "order" integer NOT NULL CHECK ("order" >= 0),
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

