name: flutter_webrtc
description: Stub package for flutter_webrtc on Windows (WebRTC not supported on Windows)
version: 0.11.7
homepage: https://github.com/flutter-webrtc/flutter-webrtc

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

